name: gradle
on:
  push:
    branches: [ main ] 
 
jobs:
  elastic:
    runs-on: centos:7
    steps:

      - name: Step 1 - Checkout dev branch from GitHub  
        uses: actions/checkout@v2
     
      - name: Upload GitHub Action workflows logs to elastic
        uses: knutfr/github-actions-to-elk@v1.0.4
        with:
          githubToken: "${{ secrets.GITHUB }}"
          githubOrg: "philips-internal"
          githubRepository: "ampm-cicd-reference-application"
          githubRunId: "${{ github.run_id }}"
          elasticHost: "https://kibana-esapm-absolute-duck.cloud.pcftest.com:443"
          elasticApiKeyId: xb4dRH8BDDAzjPaGHx59
          elasticApiKey: dA1rRhx5Qp2V1Lhl-xXcng
          elasticIndex: "github"
